### ISSUE TITLE
Errore su alcune serie

### ISSUE THREAD

**Issue by tormento** [CoffeeStraw/VVVVID-Downloader#26]
Se provate a scaricare la serie

https://www.vvvvid.it/show/1414/l-attacco-dei-giganti-la-stagione-finale

scaricando i "LIVE con Giò" (lasciamo perdere...) avverrà un errore (anche con rtmpdump.exe nel path):

```
Episodio 99: Live con Giò - scaricando

[VVVVID] Downloading JSON metadata
[VVVVID] 693713: Downloading JSON metadata
[VVVVID] 693713: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[VVVVID] 693713: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[VVVVID] 693713: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[download] Destination: \\192.168.103.59\Anime\Downloads\L'Attacco dei Giganti - La Stagione Finale - LIVE con Giò\99 - Live con Giò.m3u8
[rtmpdump] Downloaded 0 bytes


ERROR: rtmpdump exited with code 1
Traceback (most recent call last):
  File "\\192.168.103.59\Anime\VVVVID-Downloader\main.py", line 214, in <module>
    main()
  File "\\192.168.103.59\Anime\VVVVID-Downloader\main.py", line 198, in main
    dl_from_vvvvid(line, requests_obj)
  File "\\192.168.103.59\Anime\VVVVID-Downloader\main.py", line 122, in dl_from_vvvvid
    ydl.download([ep_url])
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 1683, in process_video_result
    self.process_info(new_info)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 1967, in process_info
    success = dl(filename, info_dict)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 1906, in dl
    return fd.download(name, info)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\downloader\rtmp.py", line 213, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\downloader\common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "D:\Programmi\Sistema\Python_x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: rtmpdump exited with code 1```

**Comment by CoffeeStraw** [comment]
Ciao, a me non restituisce nessun errore... Hai utilizzato lo script direttamente oppure la release Windwos?
![image](https://user-images.githubusercontent.com/16942527/113206822-3817ac00-9270-11eb-82fa-96a472dbe79d.png)

**Comment by tormento** [comment]
> Ciao, a me non restituisce nessun errore... Hai utilizzato lo script direttamente oppure la release Windows?
Scarica tutto, non solo il primo. Ho testato entrambe le versioni.

**Comment by CoffeeStraw** [comment]
Trovato il problema. Lo script prova a scaricare anche il link alla live, ma ovviamente crasha perché non trova nessun video lì. Entro oggi risolvo il problema e ricarico tutto.
