### ISSUE TITLE
Fix caratteri unicode

### ISSUE THREAD

**Issue by pdor70** [CoffeeStraw/VVVVID-Downloader#29]
Con caratteri come la "o" in JŌSUKE:

Traceback (most recent call last):
  File "main.py", line 205, in <module>
  File "main.py", line 191, in main
  File "main.py", line 109, in dl_from_vvvvid
  File "utility.py", line 112, in ffmpeg_dl
  File "C:\Users\Antonio\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 118: character maps to <undefined>

**Comment by CoffeeStraw** [comment]
Dovrei aver risolto. Fammi sapere se ci sono ancora problemi! (Se hai usato la release Windows, la aggiornerò non appena ho terminato qualche altra modifica)

**Comment by pdor70** [comment]
Thanks!!! Su linux sta girando perfettamente con docker. Appena esce la versione Windows provo anche quella. Lavoro fantastico.

**Comment by CoffeeStraw** [comment]
Fatto, fammi sapere!

**Comment by pdor70** [comment]
Perfetto anche su Windows!
