### ISSUE TITLE
ERROR: Sign in to confirm your age

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#38]
Ciao,

ecco il dettaglio:
`Stagione: EXTRA
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "youtube_dl\extractor\common.py", line 534, in extract
  File "youtube_dl\extractor\youtube.py", line 1712, in _real_extract
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 248, in <module>
  File "main.py", line 234, in main
  File "main.py", line 142, in dl_from_vvvvid
  File "youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "youtube_dl\YoutubeDL.py", line 891, in process_ie_result
  File "youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "youtube_dl\YoutubeDL.py", line 824, in wrapper
  File "youtube_dl\YoutubeDL.py", line 628, in report_error
  File "youtube_dl\YoutubeDL.py", line 598, in trouble
youtube_dl.utils.DownloadError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
[15604] Failed to execute script main`

il link della serie: https://www.vvvvid.it/show/374/prison-school

puoi darci un'occhiata?

**Comment by Bazzu85** [comment]
edit: ho visto che stavo usando la vs 1.5.1. Usando l'ultima (1.5.3) l'errore non si presenta..
scusa

**Comment by Bazzu85** [comment]
ciao, riapro perche con lo stesso link ma con il parametro -v ho un errore:
`Stagione: EXTRA
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.8.10 (CPython) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[VVVVID] Downloading JSON metadata
[VVVVID] 482348: Downloading JSON metadata
[youtube] HSvlOPMLQFQ: Downloading webpage
[youtube] HSvlOPMLQFQ: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "youtube_dl\extractor\common.py", line 534, in extract
  File "youtube_dl\extractor\youtube.py", line 1712, in _real_extract
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.

Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "youtube_dl\extractor\common.py", line 534, in extract
  File "youtube_dl\extractor\youtube.py", line 1712, in _real_extract
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 260, in <module>
  File "main.py", line 246, in main
  File "main.py", line 155, in dl_from_vvvvid
  File "youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "youtube_dl\YoutubeDL.py", line 891, in process_ie_result
  File "youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "youtube_dl\YoutubeDL.py", line 824, in wrapper
  File "youtube_dl\YoutubeDL.py", line 628, in report_error
  File "youtube_dl\YoutubeDL.py", line 598, in trouble
youtube_dl.utils.DownloadError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
[13016] Failed to execute script main
Press any key to continue . . .`

se tolgo il verbose nessun errore

**Comment by CoffeeStraw** [comment]
Ti confermo che è tutto corretto. Con il "verbose" ottieni l'errore esplicitato con l'intero stack-trace per poterlo analizzare, ma generalmente non si è interessati a queste informazioni e infatti senza verbose ottieni un output più pulito, del tipo:
```
- Episodio 01: il contenuto non è scaricabile.
È possibile che il contenuto venga fornito da un servizio esterno e/o abbia restrizioni sull'età. Il download verrà saltato.
```

È esattamente ciò che voglio, per cui nessun errore (la verbose non deve essere utilizzata per scaricare normalmente).

**Comment by Bazzu85** [comment]
Sinceramente dissento da questo ragionamento.
Se l'elaborazione senza verbose non si chiude con errori, non dovrebbe nemmeno chiudersi in errore con il verbose.
Il flow applicativo dovrebbe essere lo stesso. il concetto di verbose è dare semplicemente piu informazioni durante l'esecuzione

A supporto di ciò ti dico solo che stavo utilizzando il verbose per beccare un errore su un link successivo a https://www.vvvvid.it/show/374/prison-school.
Senza verbose il pgm arriva al punto voluto.
Con verbose si ferma a questo link..

poi eh. Io sono un programmatore cobol/db2/cics. Ci capisco poco di questi linguaggi di programmazione moderni... :D

**Comment by CoffeeStraw** [comment]
Good point. Allora dovrei rivedere il software per gestire meglio questi casi, anche se a mia memoria questo è l'unico punto. Riapro la issue per ricordarmi di fixarlo!
