### ISSUE TITLE
Impossibile eseguire download

### ISSUE THREAD

**Issue by matant94** [CoffeeStraw/VVVVID-Downloader#49]
```
Stagione: Episodi
Traceback (most recent call last):
  File "main.py", line 266, in <module>
  File "main.py", line 252, in main
  File "main.py", line 167, in dl_from_vvvvid
AttributeError: 'NoneType' object has no attribute 'group'
[23272] Failed to execute script 'main' due to unhandled exception!
```

**Comment by bubu2323** [comment]
stesso problema, hai trovato una soluzione per caso?

**Comment by AndreaCicca** [comment]
> stesso problema, hai trovato una soluzione per caso?

L'unica cosa è chiedere a @CoffeeStraw
