### ISSUE TITLE
Errore download

### ISSUE THREAD

**Issue by xMrDan** [CoffeeStraw/VVVVID-Downloader#50]
L' ultima versione(1.5.4) mi da errore e non scarica nulla
![errore vvvvid](https://user-images.githubusercontent.com/123836683/215288173-baab0c9a-ae09-4e41-983c-d5d60004e9c9.png)
:
Traceback (most recent call last):
  File "main.py", line 266, in <module>
  File "main.py", line 252, in main
  File "main.py", line 167, in dl_from_vvvvid
AttributeError: 'NoneType' object has no attribute 'group'
[11624] Failed to execute script 'main' due to unhandled exception!
Qualcuno sa dirmi perchè? Grazie in anticipo

**Comment by LukeSavefrogs** [comment]
Per caso l'url che hai dato in pasto allo script NON contiene il protocollo (`http://` o `https://`)?

**Comment by LukeSavefrogs** [comment]
Stesso problema di #49

**Comment by LukeSavefrogs** [comment]
@CoffeeStraw la variabile `infos` viene valorizzata come segue:
```json
{
	"url": "rtsp://sb.top-ix.org/videomg/_definst_/mp4:\ndUrc\x1b-",
	"format_id": "rtsp-0",
	"protocol": "rtsp",
	"ext": "unknown_video",
	"format": "rtsp-0 - unknown",
	"http_headers": {
		"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3529.3 Safari/537.36",
		"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
		"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Accept-Encoding": "gzip, deflate",
		"Accept-Language": "en-us,en;q=0.5"
	}
}
```
Il campo `infos["url"]` quindi non soddisfa mai la regex `(https.+$)`.

**Comment by xMrDan** [comment]
Si grazie, secondo me è cambiato qualcosa da parte di VVVID

**Comment by CoffeeStraw** [comment]
Yo! Scusate se ho ignorato le issues.

Ho buttato un rapido occhio, e mi sembra che VVVVID ha in effetti cambiato il modo con cui costruisce il link all'episodio. In realtá mi sembra che comunque i file siano hostati su server VVVVID, ad esempio:
https://vvvvid.akamaized.net/Dynit/SteinsGate/SteinsGate0_S01Ep01_hd-v.mp4

Per recuperare il link mi affidavo a YouTubeDL, sperando che fosse sufficientemente robusto. Non mi sembra essere piú in grado di recuperare i manifest, per cui ci sarebbe da capire come farlo da noi. Indagheró non appena mi si apre uno spiraglio di tempo 🙏🏻

**Comment by filobus97** [comment]
Stesso problema, immagino non ci sia ancora una soluzione giusto?

**Comment by RayRJJackson** [comment]
Non c'è ancora una soluzione a questo problema, immagino.

**Comment by doggerx** [comment]
Anche io confermo ancora la presenza di questo problema

**Comment by RayRJJackson** [comment]
@CoffeeStraw Ancora nessuna soluzione trovata? Non vorrei che, prima che il sito sparisca, non si trovi una soluzione a questo problema.
